# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} with Yarn
      uses: DerYeger/yarn-setup-action@v1.0.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Test Strapi part
      run: 
        cd api
        echo "Try to build strapi"
        rm -rf node_modules && yarn install --frozen-lockfile
        yarn build --if-present
        yarn test
    - name: Test Gatsby part
      run:
        cd ../web
        echo "Try to build Gatsby"
        rm -rf node_modules && yarn install --frozen-lockfile
        yarn run build --if-present
        yarn test
