# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Test "Strapi"
      run:  cd api
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: |
        npm ci
        npm run build --if-present
        npm test
        
    - name: Test "Gatsby"
      run:  cd ../web
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: |
        npm ci
        npm run build --if-present
        npm test
